# /etc/netplan/50-cloud-init.yaml
network:
    ethernets:
        enp0s2:
            dhcp4: false
            addresses:
              - 192.168.1.5/24
            routes:
              - to: default
                via: 192.168.1.254
            nameservers:
              addresses:
                - 8.8.8.8
                - 1.1.1.1