#cloud-config
# Write network configuration for eth0
write_files:
  - path: /etc/sysconfig/network-scripts/ifcfg-eth0
    content: |
      TYPE=Ethernet
      BOOTPROTO=dhcp
      NAME=eth0
      DEVICE=eth0
      ONBOOT=yes
    permissions: '0644'
    owner: root:root

# Run network setup early in the boot process
bootcmd:
  - ip link set eth0 up
  - dhclient eth0
  - sleep 10  # Wait for network to stabilize

# Update and upgrade the system
package_update: true
package_upgrade: true

# Install required packages
packages:
  - nginx
  - curl
  - iproute
  - dhclient  # Correct package for AlmaLinux

# Configure services
runcmd:
  - systemctl enable nginx
  - systemctl start nginx
  - sleep 5