#cloud-config
package_update: true
package_upgrade: true
write_files:
  - path: /etc/netplan/50-cloud-init.yaml
    content: |
      network:
        version: 2
        ethernets:
          enp0s2:
            dhcp4: false
            addresses:
              - 192.168.1.5/24
            routes:
              - to: default
                via: 192.168.1.254
            nameservers:
              addresses:
                - 8.8.8.8
                - 1.1.1.1
    permissions: '0600'

runcmd:
  - netplan apply