#cloud-config
hostname: dns-server
users:
  - name: ubuntu
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa YOUR_SSH_PUBLIC_KEY_HERE

# Update system and install prerequisites
package_update: true
package_upgrade: true
packages:
  - curl
  - wget
  - git
  - nano
  - htop
  - net-tools
  - dnsutils

# Set timezone
timezone: America/Mexico_City

# Configure network (static IP will be set by Incus)
write_files:
  - path: /tmp/pihole-setup.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      
      # Pi-hole automated installation variables
      export PIHOLE_SKIP_OS_CHECK=true
      export DEBIAN_FRONTEND=noninteractive
      
      # Create setupVars.conf for unattended installation
      mkdir -p /etc/pihole
      cat > /etc/pihole/setupVars.conf << 'SETUP_EOF'
      PIHOLE_INTERFACE=eth0
      IPV4_ADDRESS=192.168.1.10/24
      IPV6_ADDRESS=
      PIHOLE_DNS_1=1.1.1.1
      PIHOLE_DNS_2=8.8.8.8
      QUERY_LOGGING=true
      INSTALL_WEB_SERVER=true
      INSTALL_WEB_INTERFACE=true
      LIGHTTPD_ENABLED=true
      BLOCKING_ENABLED=true
      WEBPASSWORD=admin123  # Change this to a secure password
      DNSMASQ_LISTENING=local
      DNS_FQDN_REQUIRED=true
      DNS_BOGUS_PRIV=true
      DNSSEC=false
      TEMPERATUREUNIT=C
      WEBUIBOXEDLAYOUT=traditional
      PIHOLE_LOG_LEVEL=0
      PIHOLE_LOCAL_HOST_RECORD=true
      SETUP_EOF
      
      # Download and run Pi-hole installer
      curl -sSL https://install.pi-hole.net | bash /dev/stdin --unattended
      
      # Configure local domain
      echo "domain=homelab.local" >> /etc/dnsmasq.d/02-pihole-local.conf
      echo "local=/homelab.local/" >> /etc/dnsmasq.d/02-pihole-local.conf
      echo "expand-hosts" >> /etc/dnsmasq.d/02-pihole-local.conf
      echo "addn-hosts=/etc/pihole/custom.list" >> /etc/dnsmasq.d/02-pihole-local.conf
      
      # Create custom hosts file
      touch /etc/pihole/custom.list
      echo "192.168.1.10    dns-server.homelab.local" > /etc/pihole/custom.list
      
      # Restart Pi-hole FTL
      systemctl restart pihole-FTL
      
      # Configure firewall
      ufw --force enable
      ufw allow 53/tcp
      ufw allow 53/udp
      ufw allow 80/tcp
      ufw allow 443/tcp
      ufw allow 22/tcp
      
      echo "Pi-hole installation completed!"
      echo "Web interface: http://192.168.1.10/admin"
      echo "Password: admin123"

runcmd:
  - /tmp/pihole-setup.sh

final_message: "Pi-hole DNS server setup completed. Access web interface at http://192.168.1.10/admin"
